@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.coopoverhaul.common.social;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;