@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.coopmod.common.coordination;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;