@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.coopmod.common.compat.naturalabsorption;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;