@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.coopmod.common.config.dimension;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;