@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.coopoverhaul.common.event;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;