@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.coopoverhaul.common.core;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;