@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.coopoverhaul.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;