@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.coopmod.common.protection;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;