@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.coopmod.common.compat;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;