@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.coopoverhaul.api;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;